- title: true
- shields:
    style: 'flat-square'
    shields:
      - alt: 'flipactual'
        image: 'badge/😋-flipactual-218AC7.svg'
        link: 'https://www.flipactual.com/'
      - alt: 'Travis'
        image: 'travis/flipactual/fuzzy-proxy.svg'
        link: 'https://travis-ci.org/flipactual/fuzzy-proxy/'
      - alt: 'Codecov'
        image: 'codecov/c/github/flipactual/fuzzy-proxy.svg'
        link: 'https://codecov.io/gh/flipactual/fuzzy-proxy/'
      - alt: 'Node'
        image: 'node/v/fuzzy-proxy.svg'
        link: 'http://npmjs.com/package/fuzzy-proxy'
      - alt: 'NPM'
        image: 'npm/v/fuzzy-proxy.svg'
        link: 'http://npmjs.com/package/fuzzy-proxy'
- text: 'Creates an object with fuzzy matching capabilities.'
- include: './docs/scripts.md'
- jsdoc: 'index.js'
- license: true
